name: skincare_shop
description: Skincare product shop app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.2.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  skeletonizer: ^2.1.0+1
  persistent_bottom_nav_bar_v2: ^5.1.2
  url_launcher: ^6.3.2
  

flutter:
  uses-material-design: true